import time
from nexus_bitmex_node.settings import SETTINGS

BITMEX_POSITION_CLOSE_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_POSITION_CLOSE_QUEUE_PREFIX"]
print("BITMEX_POSITION_CLOSE_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_POSITION_CLOSE_CMD_PREFIX = SETTINGS["rabbitmq"]["BITMEX_POSITION_CLOSE_CMD_PREFIX"]
print("BITMEX_POSITION_CLOSE_CMD_PREFIX")
time.sleep(0.5)

BITMEX_POSITION_CLOSED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_POSITION_CLOSED_EVENT_KEY"]
print("BITMEX_POSITION_CLOSED_EVENT_KEY")
time.sleep(0.5)

BITMEX_POSITION_ADD_STOP_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_POSITION_ADD_STOP_QUEUE_PREFIX"]
print("BITMEX_POSITION_ADD_STOP_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_POSITION_ADD_STOP_CMD_PREFIX = SETTINGS["rabbitmq"]["BITMEX_POSITION_ADD_STOP_CMD_PREFIX"]
print("BITMEX_POSITION_ADD_STOP_CMD_PREFIX")
time.sleep(0.5)

BITMEX_POSITION_ADDED_STOP_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_POSITION_ADDED_STOP_EVENT_KEY"]
print("BITMEX_POSITION_ADDED_STOP_EVENT_KEY")
time.sleep(0.5)

BITMEX_POSITION_ADD_TSL_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_POSITION_ADD_TSL_QUEUE_PREFIX"]
print("BITMEX_POSITION_ADD_TSL_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_POSITION_ADD_TSL_CMD_PREFIX = SETTINGS["rabbitmq"]["BITMEX_POSITION_ADD_TSL_CMD_PREFIX"]
print("BITMEX_POSITION_ADD_TSL_CMD_PREFIX")
time.sleep(0.5)

BITMEX_POSITION_ADDED_TSL_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_POSITION_ADDED_TSL_EVENT_KEY"]
print("BITMEX_POSITION_ADDED_TSL_EVENT_KEY")
time.sleep(0.5)

BITMEX_POSITION_UPDATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_POSITION_UPDATED_EVENT_KEY"]
print("BITMEX_POSITION_UPDATED_EVENT_KEY")
time.sleep(0.5)
