from nexus_bitmex_node.settings import SETTINGS

BITMEX_CREATE_ACCOUNT_QUEUE = SETTINGS["rabbitmq"]["BITMEX_CREATE_ACCOUNT_QUEUE"]
BITMEX_CREATE_ACCOUNT_CMD_KEY = SETTINGS["rabbitmq"]["BITMEX_CREATE_ACCOUNT_CMD_KEY"]
BITMEX_ACCOUNT_CREATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ACCOUNT_CREATED_EVENT_KEY"]

BITMEX_UPDATE_ACCOUNT_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ACCOUNT_QUEUE_PREFIX"]
BITMEX_UPDATE_ACCOUNT_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ACCOUNT_CMD_KEY_PREFIX"]
BITMEX_ACCOUNT_UPDATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ACCOUNT_UPDATED_EVENT_KEY"]

BITMEX_DELETE_ACCOUNT_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_DELETE_ACCOUNT_QUEUE_PREFIX"]
BITMEX_DELETE_ACCOUNT_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_DELETE_ACCOUNT_CMD_KEY_PREFIX"]
BITMEX_ACCOUNT_DELETED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ACCOUNT_DELETED_EVENT_KEY"]

BITMEX_HEARTBEAT_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_HEARTBEAT_EVENT_KEY"]
