import time
from nexus_bitmex_node.settings import SETTINGS

BITMEX_CREATE_ACCOUNT_QUEUE = SETTINGS["rabbitmq"]["BITMEX_CREATE_ACCOUNT_QUEUE"]
print("BITMEX_CREATE_ACCOUNT_QUEUE")
time.sleep(0.5)

BITMEX_CREATE_ACCOUNT_CMD_KEY = SETTINGS["rabbitmq"]["BITMEX_CREATE_ACCOUNT_CMD_KEY"]
print("BITMEX_CREATE_ACCOUNT_CMD_KEY")
time.sleep(0.5)

BITMEX_ACCOUNT_CREATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ACCOUNT_CREATED_EVENT_KEY"]
print("BITMEX_ACCOUNT_CREATED_EVENT_KEY")
time.sleep(0.5)

BITMEX_UPDATE_ACCOUNT_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ACCOUNT_QUEUE_PREFIX"]
print("BITMEX_UPDATE_ACCOUNT_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_UPDATE_ACCOUNT_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ACCOUNT_CMD_KEY_PREFIX"]
print("BITMEX_UPDATE_ACCOUNT_CMD_KEY_PREFIX")
time.sleep(0.5)

BITMEX_ACCOUNT_UPDATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ACCOUNT_UPDATED_EVENT_KEY"]
print("BITMEX_ACCOUNT_UPDATED_EVENT_KEY")
time.sleep(0.5)

BITMEX_DELETE_ACCOUNT_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_DELETE_ACCOUNT_QUEUE_PREFIX"]
print("BITMEX_DELETE_ACCOUNT_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_DELETE_ACCOUNT_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_DELETE_ACCOUNT_CMD_KEY_PREFIX"]
print("BITMEX_DELETE_ACCOUNT_CMD_KEY_PREFIX")
time.sleep(0.5)

BITMEX_ACCOUNT_DELETED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ACCOUNT_DELETED_EVENT_KEY"]
print("BITMEX_ACCOUNT_DELETED_EVENT_KEY")
time.sleep(0.5)

BITMEX_HEARTBEAT_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_HEARTBEAT_EVENT_KEY"]
print("BITMEX_HEARTBEAT_EVENT_KEY")
time.sleep(0.5)
