from nexus_bitmex_node.settings import SETTINGS

BITMEX_CREATE_ORDER_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CREATE_ORDER_QUEUE_PREFIX"]
BITMEX_CREATE_ORDER_CMD_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CREATE_ORDER_CMD_PREFIX"]
BITMEX_ORDER_CREATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ORDER_CREATED_EVENT_KEY"]

BITMEX_UPDATE_ORDER_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ORDER_QUEUE_PREFIX"]
BITMEX_UPDATE_ORDER_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ORDER_CMD_KEY_PREFIX"]
BITMEX_ORDER_UPDATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ORDER_UPDATED_EVENT_KEY"]

BITMEX_CANCEL_ORDER_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CANCEL_ORDER_QUEUE_PREFIX"]
BITMEX_CANCEL_ORDER_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CANCEL_ORDER_CMD_KEY_PREFIX"]
BITMEX_ORDER_CANCELED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ORDER_CANCELED_EVENT_KEY"]
