import time
from nexus_bitmex_node.settings import SETTINGS

BITMEX_CREATE_ORDER_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CREATE_ORDER_QUEUE_PREFIX"]
print("BITMEX_CREATE_ORDER_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_CREATE_ORDER_CMD_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CREATE_ORDER_CMD_PREFIX"]
print("BITMEX_CREATE_ORDER_CMD_PREFIX")
time.sleep(0.5)

BITMEX_ORDER_CREATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ORDER_CREATED_EVENT_KEY"]
print("BITMEX_ORDER_CREATED_EVENT_KEY")
time.sleep(0.5)

BITMEX_UPDATE_ORDER_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ORDER_QUEUE_PREFIX"]
print("BITMEX_UPDATE_ORDER_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_UPDATE_ORDER_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_UPDATE_ORDER_CMD_KEY_PREFIX"]
print("BITMEX_UPDATE_ORDER_CMD_KEY_PREFIX")
time.sleep(0.5)

BITMEX_ORDER_UPDATED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ORDER_UPDATED_EVENT_KEY"]
print("BITMEX_ORDER_UPDATED_EVENT_KEY")
time.sleep(0.5)

BITMEX_CANCEL_ORDER_QUEUE_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CANCEL_ORDER_QUEUE_PREFIX"]
print("BITMEX_CANCEL_ORDER_QUEUE_PREFIX")
time.sleep(0.5)

BITMEX_CANCEL_ORDER_CMD_KEY_PREFIX = SETTINGS["rabbitmq"]["BITMEX_CANCEL_ORDER_CMD_KEY_PREFIX"]
print("BITMEX_CANCEL_ORDER_CMD_KEY_PREFIX")
time.sleep(0.5)

BITMEX_ORDER_CANCELED_EVENT_KEY = SETTINGS["rabbitmq"]["BITMEX_ORDER_CANCELED_EVENT_KEY"]
print("BITMEX_ORDER_CANCELED_EVENT_KEY")
time.sleep(0.5)
